// ⚠️ Arapça SAĞDAN SOLA. Metin yönü `dil.js` içinde kök öğeye yazılıyor.
// Metinlerde yön işaretleri (↑ ↓ ★ %) RTL bağlamda ters görünebilir; bu
// yüzden yüzde ve ok içeren cümleler bilerek kelimeyle kuruldu.
export const ar = {
  ad: 'Rulemix',
  oyna: 'العب', devam: 'متابعة', ayarlar: 'الإعدادات', geri: 'رجوع', tamam: 'حسناً', iptal: 'إلغاء',
  harita: 'الحملة', bolum: 'المرحلة', kilitli: 'مقفلة', kilitAcikla: 'أكمل المرحلة السابقة',
  grupKilitli: 'أكمل {n} مراحل في الفصل السابق لفتح {ad}',
  ilerleme: '{bitti}/{toplam}', yildizToplam: '{n} نجمة',
  klasik: 'الكلاسيكي', klasikMetin: 'فوق اللون نفسه، أو في أنبوب فارغ.',
  kapasite: 'السعة', kapasiteMetin: 'ارتفاعات الأنابيب مختلفة. القاعدة نفسها.',
  kilit: 'الختم', kilitMetin: 'الأنبوب الذي يمتلئ يُختم: لا يخرج منه شيء.',
  tekyon: 'اتجاه واحد', tekyonMetin: 'أنبوب المصدر يُعطي فقط، وأنبوب الوجهة يستقبل فقط.',
  menzil: 'المدى', menzilMetin: 'تنتقل الكرة إلى أنبوبين على الأكثر.',
  hamle: 'الحركات', yildiz: 'النجوم', geriAl: 'تراجع', bastan: 'إعادة', cikis: 'خروج',
  enKisa: 'الأقصر', reklamGeriAl: 'شاهد إعلاناً ‎+3', reklamCan: 'شاهد إعلاناً ‎+1 حياة',
  cozuldu: 'تم الحل', kusursuz: 'مثالي — هو الحل الأقصر نفسه.',
  hamleFazla: 'أطول من الحل الأقصر بـ {n} حركة.', ucYildizIcin: 'النجوم الثلاث تحتاج {n} حركة أو أقل.',
  ucYildizTuttu: 'بلغت عتبة النجوم الثلاث.',
  sonraki: 'المرحلة التالية', tekrar: 'حاول مجدداً', tahtadaKal: 'ابقَ على اللوحة', haritaya: 'العودة إلى الحملة',
  oldu: 'انغلقت اللوحة', olduCikmaz: 'لم تبقَ حركة ممكنة.',
  olduTuzak: 'تلك الحركة أنهت اللوحة — لا حل من هنا.',
  geriAlKurtar: 'تراجع وأنقذ اللوحة',
  canGitti: 'فقدت حياة', canKalan: 'الحيوات المتبقية: {n} من {tavan}.',
  canBitti: 'نفدت الحيوات', canDolar: 'تعود حياة بعد {sure}.', bekle: 'انتظر',
  canKapi: 'المرحلة {sira} من {ad} يمكن خسارتها — تحتاج حياة واحدة على الأقل للدخول.',
  cansizOyna: 'العب مرحلة بلا حيوات', sigInak: 'تتوفر الآن {n} مرحلة يمكن لعبها بلا حيوات.',
  cansizBolum: 'لا يمكن خسارة هذه المرحلة — مقاسة.',
  ogreticiBolum: 'مرحلة تعليمية: تعرض القاعدة ولا تستهلك حياة.',
  bitirdinBolum: 'أنهيتها — إعادة اللعب لا تكلف حياة.',
  kaybedilebilir: 'مرحلة قابلة للخسارة: إذا انتهت حركاتك أو انغلقت اللوحة تفقد حياة.',
  dilSec: 'اللغة', sifirla: 'إعادة ضبط التقدّم', sifirlaSor: 'ستُمحى كل المراحل والنجوم. هل أنت متأكد؟',
  gizlilik: 'الخصوصية', hakkinda: 'حول التطبيق',
  tamSurum: 'النسخة الكاملة', tamSurumMetin: 'بلا إعلانات ‏+ حيوات غير محدودة.',
  yukleniyor: 'جارٍ التحميل…',
  zafer: 'أحسنت!', yeniKural: 'قاعدة جديدة', basla: 'ابدأ', bolumler: 'المراحل',
  ses: 'الصوت', acik: 'تشغيل', kapali: 'إيقاف',
  tamSurumAl: 'احصل على النسخة الكاملة', tamSurumEtkin: 'النسخة الكاملة مفعّلة', geriYukle: 'استعادة المشتريات', geriYukYok: 'لا توجد مشتريات لاستعادتها.', satisHata: 'تعذّر إتمام الشراء. حاول مجدداً بعد قليل.', reklamYok: 'لا يوجد إعلان متاح الآن. حاول مجدداً بعد قليل.', reklamDeneme: 'إعلان تجريبي',
  gunluk: 'لغز اليوم', gunlukSeri: 'سلسلة: {n} يوم', paylas: 'مشاركة', kopyalandi: 'تم النسخ', gunlukBolum: 'لغز اليوم: لا يستهلك حياة، ويصل لغز جديد غداً.',
  reklamTercih: 'تفضيلات الإعلانات',
  kalanHamle: 'الحركات المتبقية {n}', olduHamle: 'انتهت حركاتك.',
}
