export const en = {
  ad: 'Rulemix',
  oyna: 'Play', devam: 'Continue', ayarlar: 'Settings', geri: 'Back', tamam: 'OK', iptal: 'Cancel',
  harita: 'Campaign', bolum: 'Level', kilitli: 'Locked', kilitAcikla: 'Finish the previous level',
  grupKilitli: 'Finish {n} levels in the previous chapter to unlock {ad}',
  ilerleme: '{bitti}/{toplam}', yildizToplam: '{n} stars',
  klasik: 'Classic', klasikMetin: 'Onto the same colour, or into an empty tube.',
  kapasite: 'Capacity', kapasiteMetin: 'Tubes are different heights. Same rule.',
  kilit: 'Seal', kilitMetin: 'A tube that fills up is sealed: nothing comes back out.',
  tekyon: 'One way', tekyonMetin: '↑ only gives, ↓ only takes.',
  menzil: 'Range', menzilMetin: 'A ball travels at most 2 tubes.',
  hamle: 'Moves', yildiz: 'Stars', geriAl: 'Undo', bastan: 'Restart', cikis: 'Quit',
  enKisa: 'Shortest', reklamGeriAl: 'Watch ad +3', reklamCan: 'Watch ad +1 life',
  cozuldu: 'Solved', kusursuz: 'Perfect — the shortest solution itself.',
  hamleFazla: '{n} moves longer than the shortest.', ucYildizIcin: '★★★ needs {n} moves or fewer.',
  ucYildizTuttu: 'You made the ★★★ threshold.',
  sonraki: 'Next level', tekrar: 'Try again', tahtadaKal: 'Stay on the board', haritaya: 'Back to campaign',
  oldu: 'Board locked', olduCikmaz: 'No legal moves left.',
  olduTuzak: 'That move killed the board — there is no solution from here.',
  geriAlKurtar: 'Undo and save it',
  canGitti: 'Lost a life', canKalan: 'Lives left: {n}/{tavan}.',
  canBitti: 'Out of lives', canDolar: 'One life returns in {sure}.', bekle: 'Wait',
  canKapi: '{ad} level {sira} can be lost — you need at least 1 life to enter.',
  cansizOyna: 'Play a life-free level', sigInak: '{n} levels are playable without lives right now.',
  cansizBolum: 'This level cannot be lost — measured.',
  ogreticiBolum: 'Teaching level: it shows the rule, no life is spent.',
  bitirdinBolum: 'Finished — replaying costs no life.',
  kaybedilebilir: 'Losable level: run out of moves or lock the board and you lose a life.',
  dilSec: 'Language', sifirla: 'Reset progress', sifirlaSor: 'All levels and stars will be erased. Are you sure?',
  gizlilik: 'Privacy', hakkinda: 'About',
  tamSurum: 'Full Version', tamSurumMetin: 'No ads + unlimited lives.',
  yukleniyor: 'Loading…',
  zafer: 'Well done!', yeniKural: 'New rule', basla: 'Start', bolumler: 'Levels',
  ses: 'Sound', acik: 'On', kapali: 'Off',
  tamSurumAl: 'Get the Full Version', tamSurumEtkin: 'Full Version active', geriYukle: 'Restore purchases', geriYukYok: 'No purchase found to restore.', satisHata: 'The purchase could not be completed. Try again in a moment.', reklamYok: 'No ad available right now. Try again in a moment.', reklamDeneme: 'Test ad',
  gunluk: 'Daily puzzle', gunlukSeri: 'Streak: {n} days', paylas: 'Share', kopyalandi: 'Copied', gunlukBolum: 'Daily puzzle: costs no life, a new one arrives tomorrow.',
  reklamTercih: 'Ad preferences',
  kalanHamle: 'Moves left {n}', olduHamle: 'You ran out of moves.',
}
