export const fr = {
  ad: 'Rulemix',
  oyna: 'Jouer', devam: 'Continuer', ayarlar: 'Réglages', geri: 'Retour', tamam: 'OK', iptal: 'Annuler',
  harita: 'Campagne', bolum: 'Niveau', kilitli: 'Verrouillé', kilitAcikla: 'Termine le niveau précédent',
  grupKilitli: 'Termine {n} niveaux du chapitre précédent pour débloquer {ad}',
  ilerleme: '{bitti}/{toplam}', yildizToplam: '{n} étoiles',
  klasik: 'Classique', klasikMetin: 'Sur la même couleur, ou dans un tube vide.',
  kapasite: 'Capacité', kapasiteMetin: 'Les tubes n’ont pas la même hauteur. Même règle.',
  kilit: 'Sceau', kilitMetin: 'Un tube qui se remplit est scellé : rien n’en ressort.',
  tekyon: 'Sens unique', tekyonMetin: '↑ ne fait que donner, ↓ ne fait que recevoir.',
  menzil: 'Portée', menzilMetin: 'Une bille va au plus à 2 tubes de distance.',
  hamle: 'Coups', yildiz: 'Étoiles', geriAl: 'Annuler', bastan: 'Recommencer', cikis: 'Quitter',
  enKisa: 'Plus court', reklamGeriAl: 'Voir une pub +3', reklamCan: 'Voir une pub +1 vie',
  cozuldu: 'Résolu', kusursuz: 'Parfait — exactement la solution la plus courte.',
  hamleFazla: '{n} coups de plus que la solution la plus courte.', ucYildizIcin: '★★★ demande {n} coups ou moins.',
  ucYildizTuttu: 'Tu as atteint le seuil ★★★.',
  sonraki: 'Niveau suivant', tekrar: 'Réessayer', tahtadaKal: 'Rester sur le plateau', haritaya: 'Retour à la campagne',
  oldu: 'Plateau bloqué', olduCikmaz: 'Plus aucun coup légal.',
  olduTuzak: 'Ce coup a tué le plateau — il n’y a plus de solution.',
  geriAlKurtar: 'Annuler et sauver',
  canGitti: 'Une vie perdue', canKalan: 'Vies restantes : {n}/{tavan}.',
  canBitti: 'Plus de vies', canDolar: 'Une vie revient dans {sure}.', bekle: 'Attendre',
  canKapi: '{ad}, niveau {sira} peut être perdu — il faut au moins 1 vie pour entrer.',
  cansizOyna: 'Jouer un niveau sans vie', sigInak: '{n} niveaux sont jouables sans vie en ce moment.',
  cansizBolum: 'Ce niveau ne peut pas être perdu — mesuré.',
  ogreticiBolum: 'Niveau d’apprentissage : il montre la règle, aucune vie dépensée.',
  bitirdinBolum: 'Terminé — le rejouer ne coûte aucune vie.',
  kaybedilebilir: 'Niveau perdable : plus de coups ou plateau bloqué, et tu perds une vie.',
  dilSec: 'Langue', sifirla: 'Réinitialiser la progression', sifirlaSor: 'Tous les niveaux et étoiles seront effacés. Confirmer ?',
  gizlilik: 'Confidentialité', hakkinda: 'À propos',
  tamSurum: 'Version complète', tamSurumMetin: 'Sans publicité + vies illimitées.',
  yukleniyor: 'Chargement…',
  zafer: 'Bravo !', yeniKural: 'Nouvelle règle', basla: 'Jouer', bolumler: 'Niveaux',
  ses: 'Son', acik: 'Activé', kapali: 'Désactivé',
  tamSurumAl: 'Obtenir la version complète', tamSurumEtkin: 'Version complète active', geriYukle: 'Restaurer les achats', geriYukYok: 'Aucun achat à restaurer.', satisHata: 'L’achat n’a pas pu aboutir. Réessaie dans un instant.', reklamYok: 'Aucune pub disponible pour le moment. Réessaie dans un instant.', reklamDeneme: 'Pub de test',
  gunluk: 'Puzzle du jour', gunlukSeri: 'Série : {n} jours', paylas: 'Partager', kopyalandi: 'Copié', gunlukBolum: 'Puzzle du jour : aucune vie dépensée, un nouveau arrive demain.',
  reklamTercih: 'Préférences publicitaires',
  kalanHamle: 'Coups restants {n}', olduHamle: 'Tu n’as plus de coups.',
}
