export const it = {
  ad: 'Rulemix',
  oyna: 'Gioca', devam: 'Continua', ayarlar: 'Impostazioni', geri: 'Indietro', tamam: 'OK', iptal: 'Annulla',
  harita: 'Campagna', bolum: 'Livello', kilitli: 'Bloccato', kilitAcikla: 'Completa il livello precedente',
  grupKilitli: 'Completa {n} livelli del capitolo precedente per sbloccare {ad}',
  ilerleme: '{bitti}/{toplam}', yildizToplam: '{n} stelle',
  klasik: 'Classico', klasikMetin: 'Sullo stesso colore, o in una provetta vuota.',
  kapasite: 'Capacità', kapasiteMetin: 'Le provette hanno altezze diverse. Stessa regola.',
  kilit: 'Sigillo', kilitMetin: 'Una provetta che si riempie viene sigillata: non esce più nulla.',
  tekyon: 'Senso unico', tekyonMetin: '↑ dà soltanto, ↓ riceve soltanto.',
  menzil: 'Portata', menzilMetin: 'Una pallina arriva al massimo a 2 provette di distanza.',
  hamle: 'Mosse', yildiz: 'Stelle', geriAl: 'Annulla', bastan: 'Ricomincia', cikis: 'Esci',
  enKisa: 'Più corta', reklamGeriAl: 'Guarda un annuncio +3', reklamCan: 'Guarda un annuncio +1 vita',
  cozuldu: 'Risolto', kusursuz: 'Perfetto — esattamente la soluzione più corta.',
  hamleFazla: '{n} mosse in più della soluzione più corta.', ucYildizIcin: '★★★ richiede {n} mosse o meno.',
  ucYildizTuttu: 'Hai raggiunto la soglia ★★★.',
  sonraki: 'Livello successivo', tekrar: 'Riprova', tahtadaKal: 'Resta sulla plancia', haritaya: 'Torna alla campagna',
  oldu: 'Plancia bloccata', olduCikmaz: 'Non restano mosse legali.',
  olduTuzak: 'Quella mossa ha ucciso la plancia — da qui non c’è soluzione.',
  geriAlKurtar: 'Annulla e salva',
  canGitti: 'Hai perso una vita', canKalan: 'Vite rimaste: {n}/{tavan}.',
  canBitti: 'Vite finite', canDolar: 'Una vita torna tra {sure}.', bekle: 'Aspetta',
  canKapi: '{ad}, livello {sira} si può perdere — serve almeno 1 vita per entrare.',
  cansizOyna: 'Gioca un livello senza vite', sigInak: 'Al momento {n} livelli sono giocabili senza vite.',
  cansizBolum: 'Questo livello non si può perdere — misurato.',
  ogreticiBolum: 'Livello introduttivo: mostra la regola, non costa vite.',
  bitirdinBolum: 'Completato — rigiocarlo non costa vite.',
  kaybedilebilir: 'Livello perdibile: se finisci le mosse o blocchi il tabellone, perdi una vita.',
  dilSec: 'Lingua', sifirla: 'Azzera i progressi', sifirlaSor: 'Tutti i livelli e le stelle verranno cancellati. Sei sicuro?',
  gizlilik: 'Privacy', hakkinda: 'Informazioni',
  tamSurum: 'Versione Completa', tamSurumMetin: 'Senza pubblicità + vite illimitate.',
  yukleniyor: 'Caricamento…',
  zafer: 'Ottimo!', yeniKural: 'Nuova regola', basla: 'Inizia', bolumler: 'Livelli',
  ses: 'Audio', acik: 'Attivo', kapali: 'Disattivo',
  tamSurumAl: 'Ottieni la Versione Completa', tamSurumEtkin: 'Versione Completa attiva', geriYukle: 'Ripristina acquisti', geriYukYok: 'Nessun acquisto da ripristinare.', satisHata: 'Non è stato possibile completare l’acquisto. Riprova tra poco.', reklamYok: 'Nessun annuncio disponibile al momento. Riprova tra poco.', reklamDeneme: 'Annuncio di prova',
  gunluk: 'Rompicapo del giorno', gunlukSeri: 'Serie: {n} giorni', paylas: 'Condividi', kopyalandi: 'Copiato', gunlukBolum: 'Rompicapo del giorno: non costa vite, domani ne arriva uno nuovo.',
  reklamTercih: 'Preferenze annunci',
  kalanHamle: 'Mosse rimaste {n}', olduHamle: 'Hai finito le mosse.',
}
