export const ja = {
  ad: 'Rulemix',
  oyna: 'あそぶ', devam: 'つづきから', ayarlar: '設定', geri: '戻る', tamam: 'OK', iptal: 'キャンセル',
  harita: 'キャンペーン', bolum: 'レベル', kilitli: 'ロック中', kilitAcikla: '前のレベルをクリアしてください',
  grupKilitli: '{ad} を開くには前の章で {n} レベルをクリアしてください',
  ilerleme: '{bitti}/{toplam}', yildizToplam: 'スター {n}',
  klasik: 'クラシック', klasikMetin: '同じ色の上か、空のチューブへ。',
  kapasite: '容量', kapasiteMetin: 'チューブの高さが違います。ルールは同じ。',
  kilit: '封印', kilitMetin: '満杯になったチューブは封印され、取り出せません。',
  tekyon: '一方通行', tekyonMetin: '↑ は出すだけ、↓ は受けるだけ。',
  menzil: '射程', menzilMetin: 'ボールは最大 2 本先のチューブまで。',
  hamle: '手数', yildiz: 'スター', geriAl: '元に戻す', bastan: 'やり直す', cikis: 'やめる',
  enKisa: '最短', reklamGeriAl: '広告を見る +3', reklamCan: '広告を見る +ライフ 1',
  cozuldu: 'クリア', kusursuz: '完璧 — 最短手数そのものです。',
  hamleFazla: '最短より {n} 手多い。', ucYildizIcin: '★★★ には {n} 手以内が必要です。',
  ucYildizTuttu: '★★★ の基準に届きました。',
  sonraki: '次のレベル', tekrar: 'もう一度', tahtadaKal: '盤面に残る', haritaya: 'キャンペーンへ戻る',
  oldu: '盤面が詰みました', olduCikmaz: '打てる手がありません。',
  olduTuzak: 'その一手で盤面が詰みました — ここから解はありません。',
  geriAlKurtar: '戻して立て直す',
  canGitti: 'ライフを 1 失いました', canKalan: '残りライフ: {n}/{tavan}。',
  canBitti: 'ライフ切れ', canDolar: '{sure} 後にライフが 1 回復します。', bekle: '待つ',
  canKapi: '{ad} レベル {sira} は失敗しうるレベルです。入るにはライフが 1 以上必要です。',
  cansizOyna: 'ライフ不要のレベルで遊ぶ', sigInak: '現在 {n} レベルがライフなしで遊べます。',
  cansizBolum: 'このレベルは負けようがありません — 計測済みです。',
  ogreticiBolum: 'チュートリアル：ルールを示すだけで、ライフは減りません。',
  bitirdinBolum: 'クリア済み — 再挑戦にライフは要りません。',
  kaybedilebilir: '失敗しうるステージ：手数がなくなるか盤面が詰むとライフが減ります。',
  dilSec: '言語', sifirla: '進行状況をリセット', sifirlaSor: 'すべてのレベルとスターが消えます。よろしいですか？',
  gizlilik: 'プライバシー', hakkinda: 'このアプリについて',
  tamSurum: 'フルバージョン', tamSurumMetin: '広告なし＋ライフ無制限。',
  yukleniyor: '読み込み中…',
  zafer: 'クリア！', yeniKural: '新しいルール', basla: 'スタート', bolumler: 'レベル一覧',
  ses: 'サウンド', acik: 'オン', kapali: 'オフ',
  tamSurumAl: 'フルバージョンを入手', tamSurumEtkin: 'フルバージョン有効', geriYukle: '購入を復元', geriYukYok: '復元できる購入が見つかりません。', satisHata: '購入を完了できませんでした。少し待ってからもう一度お試しください。', reklamYok: '今は広告がありません。少し待ってからもう一度お試しください。', reklamDeneme: 'テスト広告',
  gunluk: '今日のパズル', gunlukSeri: '連続 {n} 日', paylas: 'シェア', kopyalandi: 'コピーしました', gunlukBolum: '今日のパズル：ライフは減りません。明日は新しい問題が届きます。',
  reklamTercih: '広告の設定',
  kalanHamle: '残り {n} 手', olduHamle: '手数がなくなりました。',
}
