export const pt = {
  ad: 'Rulemix',
  oyna: 'Jogar', devam: 'Continuar', ayarlar: 'Definições', geri: 'Voltar', tamam: 'OK', iptal: 'Cancelar',
  harita: 'Campanha', bolum: 'Nível', kilitli: 'Bloqueado', kilitAcikla: 'Termina o nível anterior',
  grupKilitli: 'Termina {n} níveis do capítulo anterior para desbloquear {ad}',
  ilerleme: '{bitti}/{toplam}', yildizToplam: '{n} estrelas',
  klasik: 'Clássico', klasikMetin: 'Sobre a mesma cor, ou num tubo vazio.',
  kapasite: 'Capacidade', kapasiteMetin: 'Os tubos têm alturas diferentes. Mesma regra.',
  kilit: 'Selo', kilitMetin: 'Um tubo que enche fica selado: nada volta a sair.',
  tekyon: 'Sentido único', tekyonMetin: '↑ só dá, ↓ só recebe.',
  menzil: 'Alcance', menzilMetin: 'Uma bola viaja no máximo 2 tubos.',
  hamle: 'Jogadas', yildiz: 'Estrelas', geriAl: 'Desfazer', bastan: 'Recomeçar', cikis: 'Sair',
  enKisa: 'Mais curta', reklamGeriAl: 'Ver anúncio +3', reklamCan: 'Ver anúncio +1 vida',
  cozuldu: 'Resolvido', kusursuz: 'Perfeito — exatamente a solução mais curta.',
  hamleFazla: '{n} jogadas a mais do que a solução mais curta.', ucYildizIcin: '★★★ exige {n} jogadas ou menos.',
  ucYildizTuttu: 'Alcançaste o limite ★★★.',
  sonraki: 'Nível seguinte', tekrar: 'Tentar de novo', tahtadaKal: 'Ficar no tabuleiro', haritaya: 'Voltar à campanha',
  oldu: 'Tabuleiro bloqueado', olduCikmaz: 'Não restam jogadas legais.',
  olduTuzak: 'Essa jogada matou o tabuleiro — daqui não há solução.',
  geriAlKurtar: 'Desfazer e salvar',
  canGitti: 'Perdeste uma vida', canKalan: 'Vidas restantes: {n}/{tavan}.',
  canBitti: 'Sem vidas', canDolar: 'Uma vida volta em {sure}.', bekle: 'Esperar',
  canKapi: '{ad}, nível {sira} pode ser perdido — precisas de pelo menos 1 vida.',
  cansizOyna: 'Jogar um nível sem vidas', sigInak: 'Neste momento {n} níveis são jogáveis sem vidas.',
  cansizBolum: 'Este nível não pode ser perdido — medido.',
  ogreticiBolum: 'Nível de aprendizagem: mostra a regra, não gasta vida.',
  bitirdinBolum: 'Concluído — repetir não custa vida.',
  kaybedilebilir: 'Nível que pode ser perdido: se as jogadas acabarem ou o tabuleiro travar, você perde uma vida.',
  dilSec: 'Idioma', sifirla: 'Repor progresso', sifirlaSor: 'Todos os níveis e estrelas serão apagados. Tens a certeza?',
  gizlilik: 'Privacidade', hakkinda: 'Acerca',
  tamSurum: 'Versão Completa', tamSurumMetin: 'Sem anúncios + vidas ilimitadas.',
  yukleniyor: 'A carregar…',
  zafer: 'Muito bem!', yeniKural: 'Nova regra', basla: 'Começar', bolumler: 'Níveis',
  ses: 'Som', acik: 'Ligado', kapali: 'Desligado',
  tamSurumAl: 'Obter a Versão Completa', tamSurumEtkin: 'Versão Completa ativa', geriYukle: 'Restaurar compras', geriYukYok: 'Nenhuma compra para restaurar.', satisHata: 'Não foi possível concluir a compra. Tente de novo daqui a pouco.', reklamYok: 'Nenhum anúncio disponível agora. Tente de novo daqui a pouco.', reklamDeneme: 'Anúncio de teste',
  gunluk: 'Desafio diário', gunlukSeri: 'Sequência: {n} dias', paylas: 'Compartilhar', kopyalandi: 'Copiado', gunlukBolum: 'Desafio diário: não custa vida, amanhã chega um novo.',
  reklamTercih: 'Preferências de anúncios',
  kalanHamle: 'Jogadas restantes {n}', olduHamle: 'Suas jogadas acabaram.',
}
