export const tr = {
  ad: 'Rulemix',
  oyna: 'Oyna', devam: 'Devam et', ayarlar: 'Ayarlar', geri: 'Geri', tamam: 'Tamam', iptal: 'Vazgeç',
  harita: 'Kampanya', bolum: 'Bölüm', kilitli: 'Kilitli', kilitAcikla: 'Önceki bölümü bitir',
  grupKilitli: '{ad} açılması için önceki grupta {n} bölüm bitmeli',
  ilerleme: '{bitti}/{toplam}', yildizToplam: '{n} yıldız',
  klasik: 'Klasik', klasikMetin: 'Aynı renk üstüne ya da boş tüpe.',
  kapasite: 'Kapasite', kapasiteMetin: 'Tüplerin boyu eşit değil. Kural aynı.',
  kilit: 'Kilit', kilitMetin: 'Dolan tüp mühürlenir: içinden top alınamaz.',
  tekyon: 'Tek yön', tekyonMetin: '↑ yalnızca verir, ↓ yalnızca alır.',
  menzil: 'Menzil', menzilMetin: 'Top en fazla 2 tüp ötesine gider.',
  hamle: 'Hamle', yildiz: 'Yıldız', geriAl: 'Geri al', bastan: 'Baştan', cikis: 'Çık',
  enKisa: 'En kısa', reklamGeriAl: 'Reklam izle +3', reklamCan: 'Reklam izle +1 can',
  cozuldu: 'Çözüldü', kusursuz: 'Kusursuz — en kısa çözümün kendisi.',
  hamleFazla: 'En kısasından {n} hamle uzun.', ucYildizIcin: '★★★ için {n} hamle ya da altı.',
  ucYildizTuttu: '★★★ eşiğini tutturdun.',
  sonraki: 'Sonraki bölüm', tekrar: 'Tekrar dene', tahtadaKal: 'Tahtada kal', haritaya: 'Haritaya dön',
  oldu: 'Tahta kilitlendi', olduCikmaz: 'Yasal hamle kalmadı.',
  olduTuzak: 'Son hamle tahtayı öldürdü — bu noktadan çözüm yok.',
  geriAlKurtar: 'Geri al ve kurtar',
  canGitti: 'Bir can gitti', canKalan: 'Kalan can: {n}/{tavan}.',
  canBitti: 'Canlar bitti', canDolar: 'Bir can {sure} sonra dolar.', bekle: 'Bekle',
  canKapi: '{ad} {sira}. bölüm kaybedilebilir — girmek için en az 1 can gerekiyor.',
  cansizOyna: 'Cansız bölüm oyna', sigInak: 'Şu an {n} bölüm cansız oynanabilir.',
  cansizBolum: 'Bu bölümde kaybetmek imkânsız — ölçüldü.',
  ogreticiBolum: 'Öğretici bölüm: kuralı gösterir, can harcanmaz.',
  bitirdinBolum: 'Bitirdin — tekrar oynamak can yakmaz.',
  kaybedilebilir: 'Kaybedilebilir bölüm: hamlen biterse ya da tahta kilitlenirse can gider.',
  dilSec: 'Dil', sifirla: 'İlerlemeyi sıfırla', sifirlaSor: 'Bütün bölümler ve yıldızlar silinecek. Emin misin?',
  gizlilik: 'Gizlilik', hakkinda: 'Hakkında',
  tamSurum: 'Tam Sürüm', tamSurumMetin: 'Reklamsız + sınırsız can.',
  yukleniyor: 'Yükleniyor…',
  zafer: 'Harika!', yeniKural: 'Yeni kural', basla: 'Başla', bolumler: 'Bölümler',
  ses: 'Ses', acik: 'Açık', kapali: 'Kapalı',
  tamSurumAl: 'Tam Sürümü al', tamSurumEtkin: 'Tam Sürüm etkin', geriYukle: 'Satın alımları geri yükle', geriYukYok: 'Geri yüklenecek satın alma bulunamadı.', satisHata: 'Satın alma tamamlanamadı. Biraz sonra yeniden dene.', reklamYok: 'Şu an reklam yok. Biraz sonra yeniden dene.', reklamDeneme: 'Deneme reklamı',
  gunluk: 'Günlük bulmaca', gunlukSeri: 'Seri: {n} gün', paylas: 'Paylaş', kopyalandi: 'Kopyalandı', gunlukBolum: 'Günlük bulmaca: can harcanmaz, yarın yenisi gelir.',
  reklamTercih: 'Reklam tercihleri',
  kalanHamle: 'Kalan hamle {n}', olduHamle: 'Hamle hakkın bitti.',
}
